consolidate code in single branch
lightstep/python-opentelemetry-walkthrough pull request #6
Opened 2019-10-24 20:30 UTC by mauriciovasquezbernal

Instead of having a branch with instrumentation and another without,
consolidate everything under the same branch.

Solves: https://github.com/lightstep/python-opentelemetry-walkthrough/issues/5

2019-10-24 21:07 UTC, ocelotl requested changes
Only minimal changes requested, thanks @mauriciovasquezbernal !

2019-10-24 21:07 UTC, ocelotl commented on README.rst
> +We encorage readers to follow this guide to add intrumentation to
Couple or typos here: `encourage`, `instrumentation`

2019-10-25 11:56 UTC, mauriciovasquezbernal commented
I fixed those typos, thanks @ocelotl

2019-10-25 15:07 UTC, ocelotl approved these changes

2019-10-25 15:07 UTC, merged